//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 01:30:09 AM CET 
//


package com.pa165.ddtroops.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pa165.ddtroops.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pa165.ddtroops.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetHeroByNameResponse }
     * 
     */
    public GetHeroByNameResponse createGetHeroByNameResponse() {
        return new GetHeroByNameResponse();
    }

    /**
     * Create an instance of {@link Hero }
     * 
     */
    public Hero createHero() {
        return new Hero();
    }

    /**
     * Create an instance of {@link GetHeroByNameRequest }
     * 
     */
    public GetHeroByNameRequest createGetHeroByNameRequest() {
        return new GetHeroByNameRequest();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Troop }
     * 
     */
    public Troop createTroop() {
        return new Troop();
    }

}
