//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 01:30:09 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pa165.com/ddtroops/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pa165.ddtroops.soap;
